// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdIWtyWcj0VsiHyuAoo0RS-rtj3tVJAIM',
    appId: '1:1019231599687:web:4c8c938b184133eb894562',
    messagingSenderId: '1019231599687',
    projectId: 'wedding-planner-ab1a4',
    authDomain: 'wedding-planner-ab1a4.firebaseapp.com',
    storageBucket: 'wedding-planner-ab1a4.firebasestorage.app',
    measurementId: 'G-JQ93GQNK33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDniSdzN3K-LY7yC63Gn98woWKZe6FJ9so',
    appId: '1:1019231599687:android:c3de66aadb5b22ef894562',
    messagingSenderId: '1019231599687',
    projectId: 'wedding-planner-ab1a4',
    storageBucket: 'wedding-planner-ab1a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWyw8oc7izbRdEY_--vzOS231dlPJZHI4',
    appId: '1:1019231599687:ios:69cefe76c68ab849894562',
    messagingSenderId: '1019231599687',
    projectId: 'wedding-planner-ab1a4',
    storageBucket: 'wedding-planner-ab1a4.firebasestorage.app',
    iosBundleId: 'com.example.providerTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWyw8oc7izbRdEY_--vzOS231dlPJZHI4',
    appId: '1:1019231599687:ios:69cefe76c68ab849894562',
    messagingSenderId: '1019231599687',
    projectId: 'wedding-planner-ab1a4',
    storageBucket: 'wedding-planner-ab1a4.firebasestorage.app',
    iosBundleId: 'com.example.providerTest',
  );
}
